name: Deploy to EC2

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 저장소 체크아웃
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. SSH로 EC2 서버에 연결
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          cd ~/app/square-blitz
          git pull origin main
          docker-compose down
          docker-compose build
          docker-compose up -d
